baseURL = 'https://alexsun.one'
languageCode = 'en-us'
title = "Alex's site"

theme = 'hugo-PaperMod'
summaryLength = 2
hasCJKLanguage = true
[taxonomies]
     category = 'categories'
     tag = 'tags'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'],['$','$']]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"          # å¯æ¢æˆ dracula, github-dark, solarized-dark ç­‰
[menu]
    [[menu.main]]
        name = 'ğŸ Home'
        url = '/'
        weight = 1
    [[menu.main]]
        name = 'ğŸ“‚Cat'
        url = '/categories/'
        weight = 2
    [[menu.main]]
        name = 'ğŸ·ï¸Tag'
        url = '/tags/'
        weight = 3
    [[menu.main]]
        name = 'ğŸ“œArch'
        url = '/archive/'
        weight = 4
    [[menu.main]]
        name = 'ğŸ”'
        url = '/search/'
        weight = 5
[params]
  math = true
  ShowFullTextContent = false
  ShowToc = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  #ShowWordCount = true
  #ShowReadingTime = true
  [params.homeInfoParams]
	Title = 'AlexSun'
	content = '*Live free or die*<br>ä¸è‡ªç”±ï¼Œæ¯‹å®æ­»'
  [[params.socialIcons]]
	  name = 'BiliBili'
	  url = 'https://b23.tv/D3Iy4sQ'
  [[params.socialIcons]]
	  name = 'Coolapk'
	  url = 'http://www.coolapk.com/u/14103126'
  [[params.socialIcons]]
	  name = 'Zhihu'
	  url = 'https://www.zhihu.com/people/mei-you-gan-qing-de-ming-ling-shi'
  [[params.socialIcons]]
    name = 'GitHub'
    url = 'https://github.com/SunIsAlex'
  [params.assets]
    disableHLJS = true
[outputs]
home = ["HTML", "RSS", "JSON"]


[module]
  [[module.imports]]
    path = "github.com/SunIsAlex/hugo-notice-papermod"
  [[module.imports]]
    path = "hugo-PaperMod"

